-- Oracle用スキーマ定義
-- 1. products table
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(255) NOT NULL,
    price NUMBER NOT NULL
);

-- 2. orders table
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_datetime TIMESTAMP NOT NULL
);

-- 3. order_details table
CREATE TABLE order_details (
    order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL REFERENCES orders(order_id),
    product_id NUMBER NOT NULL REFERENCES products(product_id),
    quantity NUMBER NOT NULL
);

-- 4. daily_sales_summary table (Work Table)
CREATE TABLE daily_sales_summary (
    summary_date DATE NOT NULL,
    product_id NUMBER NOT NULL,
    total_quantity_sold NUMBER NOT NULL,
    total_sales_amount NUMBER NOT NULL,
    CONSTRAINT pk_daily_sales_summary PRIMARY KEY (summary_date, product_id)
);
