CREATE OR REPLACE PROCEDURE CREATE_TESTDATE 
(
  START_DATE IN DATE , END_DATE IN DATE 
) 
AS 
new_order_id NUMBER;
v_date DATE;
BEGIN
v_date := START_DATE;
 WHILE (v_date<=END_DATE) LOOP
 INSERT INTO ORDERS(ORDER_DATETIME)
 VALUES(v_date + (DBMS_RANDOM.VALUE *1))
 RETURNING ORDER_ID INTO new_order_id;

 FOR i IN 1 .. TRUNC(DBMS_RANDOM.VALUE(1, 4)) LOOP
 INSERT INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,QUANTITY) 
 VALUES(
 new_order_id,
 TRUNC(DBMS_RANDOM.value(1,6)),
 TRUNC(DBMS_RANDOM.value(1,11))
 );
 END LOOP;
 v_date :=v_date + 1;
END LOOP; 
END CREATE_TESTDATE;
